### ISSUE TITLE
Specify uTLS config

### ISSUE THREAD

**Issue by ghost** [fedosgad/mirror_proxy#2]
![Screenshot 2022-11-24 at 11 22 28](https://user-images.githubusercontent.com/118858207/203772287-223c2448-594e-45a5-81e2-f9e1f1180800.png)

What kind of upstream proxies are you suggesting here? If **mitmproxy** is used upstream (or downstream for that matter) it defeats the purpose of the fingerprint mirroring

Would it be possible to change **mirror_proxy** to _set_ a particular uTLS config, instead of trying to mirror it from the original packet?

**Comment by fedosgad** [comment]
Hello and sorry for delayed answer!

Upstream proxy is a usual http/https/socks proxy. When reversing mobile applications or websites, you may need to redirect your traffic through an IP with specific geo. That's why this option exists (mitmproxy, for example, cannot use socks proxy as an upstream proxy, which is shameful).

Yes, it is indeed possible (actually, beta version worked exactly this way), but I don't plan to implement it because fingerprints must be maintained up-to-date, and I've got better things to do. Good starting fingerprint set can be obtained from [utls](https://github.com/refraction-networking/utls), there's a new maintainer nowadays. If you need some advice on this, feel free to ask.

**Comment by fedosgad** [comment]
Closing this as wontfix.
