### ISSUE TITLE
Inspecting & modifying requests

### ISSUE THREAD

**Issue by chribro88** [fedosgad/mirror_proxy#3]
Hello,

Can Mirror Proxy be used to send the modified requests or just inspect (I guess that's what you mean by passive right?)

Say I want to extract a HTTPs header, and use that value to modify the CONNECT headers (or --proxy-header in cURL), would that be possible? I'm assuming it would require a option Simaliar to mitmproxy's 'lazy'...

Cheers

**Comment by fedosgad** [comment]
Hello!
mirror_proxy has been written as an inspection tool. Modifying data stream inside TLS tunnel is intentionally not supported, because it is not limited to HTTP, but can also be gRPC or anything else.
If you want to process this data, you can modify functions in https://github.com/fedosgad/mirror_proxy/blob/master/tls_hijacker.go and replace simple `io.Copy` with your logic (but you'll need to parse HTTP(/2) request/response structures by hand).

**Comment by fedosgad** [comment]
Closing this as wontfix.
